services:
  orbitsphere-database:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=orbitsphere
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
