services:
  events:
    image: raj18110mazumder/orbitsphere-events:latest
    env_file: ../.env
  provisioner:
    image: raj18110mazumder/orbitsphere-provisioner:latest
    env_file: ../.env
  terminator:
    image: raj18110mazumder/orbitsphere-terminator:latest
    env_file: ../.env
