networks:
  orbitsphere:
    driver: bridge

services:
  kafka:
    restart: always
    networks:
      - orbitsphere
    image: "bitnami/kafka:latest"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    volumes:
      - ./data/kafka:/bitnami/kafka
  indexer:
    image: raj18110mazumder/orbitsphere-indexer:latest
    restart: always
    depends_on:
      - kafka
    networks:
      - orbitsphere
    env_file: ../.env
    environment:
      - KAFKA_CONNECTION_URL=kafka:9092

  provisioner:
    image: raj18110mazumder/orbitsphere-provisioner:latest
    restart: always
    depends_on:
      - kafka
    networks:
      - orbitsphere
    env_file: ../.env
    environment:
      - KAFKA_CONNECTION_URL=kafka:9092

  terminator:
    image: raj18110mazumder/orbitsphere-terminator:latest
    restart: always
    depends_on:
      - kafka
    networks:
      - orbitsphere
    env_file: ../.env
    environment:
      - KAFKA_CONNECTION_URL=kafka:9092

  scheduler:
    image: raj18110mazumder/orbitsphere-scheduler:latest
    restart: always
    depends_on:
      - kafka
    networks:
      - orbitsphere
    env_file: ../.env
    environment:
      - KAFKA_CONNECTION_URL=kafka:9092
