services:
  orbitsphere-database:
    image: postgres:alpine
    restart: always
    env_file:
      - ../.env
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
